### ISSUE TITLE
cut site

### ISSUE THREAD

**Issue by mfazel** [StevenWingett/HiCUP#51]
This is more of a question than an issue!
I'm using HiCUP in an NG3C experiment that uses dpnii but the cut sites are not biotinylated. I believe HiCUP assumes the ends are biotinylated and I could not find a place in config file to specify that compare to some other softwares. Would it affect my results or how I should proceed?
I appreciate any suggestions.

**Comment by StevenWingett** [comment]
Hi,

Is the --no-fill option what you need (since the Hi-C ligation junction will not be present in the sequence read, but instead the restriction fragment sequence will be present):

--nofill  - Hi-C protocol did NOT include a fill-in of sticky ends prior to ligation step and therefore FASTQ reads shall be truncated at the Hi-C restriction enzyme cut site (if present) sequence is encountered.

Does that help?

All the best,
Steven

**Comment by mfazel** [comment]
Hi Steven,
YES, I don't know for some reason I did not see such an obvious option :-( maybe because I was looking more into the config file than the function itself! Anyways, I also had a coupled of questions out of my curiosity. Can user define the amount of memory is being used in a run (total or per thread)? and Can user change the default options for aligners? I'm sorry if these are already explained somewhere that I have not read.

Thanks,
Mehdi

**Comment by StevenWingett** [comment]
Hi Mehdi,

Ah good, I'm glad that was helpful. 

You will have to manage the memory using your system (presumably you are running HiCUP locally on a Linux machine, or using a SLURM or Grid Engine setup).  HiCUP does not have options  to pass extra parameters to the aligner (typically Bowtie2).  You will need to edit the HiCUP code to do this, although for most Hi-C experiments I would advise against this.

All the best,

Steven
